name: start-test

on: 
  - push
  - pull_request

env: 
  CI: true

jobs:
  
  start_test:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '24.12'
          cache: 'npm'

      - name: started make setup
        run: make setup

      - name: started lint
        run: make lint

      - name: started make test
        run: make test

      - name: Print Hello from Hexlet
      - uses: hexlet-components/hello-from-hexlet-action@release